# Generated by Django 5.1.3 on 2024-11-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCSCAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncbi_accession_number', models.CharField(max_length=50, unique=True)),
                ('refseq_assembly_id', models.CharField(max_length=50)),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=100)),
                ('biosample', models.CharField(max_length=50)),
                ('bioproject', models.CharField(max_length=50)),
                ('assembly_date', models.DateField()),
            ],
            options={
                'db_table': 'ucsc_assemblies',
            },
        ),
    ]
