# Generated by Django 5.1.3 on 2024-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0002_publication_cardmodel_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='publications',
            field=models.ManyToManyField(db_table='publication_2_card_model', to='bad_bac_exercise.publication'),
        ),
    ]
