# Generated by Django 5.1.3 on 2024-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0003_alter_cardmodel_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='publications',
            field=models.ManyToManyField(db_table='card_model_2_publication', to='bad_bac_exercise.publication'),
        ),
    ]
