# Generated by Django 5.1.3 on 2024-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0003_pdbstructure_drug_class_gene2ucscassembly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20, unique=True)),
                ('card_description', models.TextField()),
            ],
            options={
                'db_table': 'card_model',
                'db_table_comment': 'CARD refers to Comprehensive Antibiotic Resistance Database',
            },
        ),
        migrations.DeleteModel(
            name='CARDModelDescription',
        ),
        migrations.RenameField(
            model_name='pdbstructure',
            old_name='antibio_res_mutation',
            new_name='abr_mutations',
        ),
        migrations.RemoveField(
            model_name='antibioticresmutation',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='pdbstructure',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='pdbstructure',
            name='drug_class',
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='genes',
            field=models.ManyToManyField(db_table='abrm_2_gene', to='bad_bac_exercise.gene'),
        ),
        migrations.AddField(
            model_name='pdbstructure',
            name='drug_classes',
            field=models.ManyToManyField(db_table='pdb_2_drug_class', to='bad_bac_exercise.drugclass'),
        ),
        migrations.AddField(
            model_name='pdbstructure',
            name='drugs',
            field=models.ManyToManyField(db_table='pdb_2_drug', to='bad_bac_exercise.drug'),
        ),
        migrations.AddField(
            model_name='taxonomyname',
            name='tax_id',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='taxonomyname',
            name='tax_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='antibioticresmutation',
            name='drug_classes_affected',
            field=models.ManyToManyField(db_table='abrm_2_drug_class', to='bad_bac_exercise.drugclass'),
        ),
        migrations.AlterField(
            model_name='antibioticresmutation',
            name='drugs_affected',
            field=models.ManyToManyField(db_table='abrm_2_drug', to='bad_bac_exercise.drug'),
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='card_models',
            field=models.ManyToManyField(db_table='abrm_2_card_model', to='bad_bac_exercise.cardmodel'),
        ),
    ]
