# Generated by Django 5.1.3 on 2024-11-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0004_cardmodel_delete_cardmodeldescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibioticresmutation',
            name='dna',
        ),
    ]
