# Generated by Django 5.1.3 on 2024-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0004_alter_cardmodel_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb2gene',
            name='gene_seq_aligned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='pdb_chain',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='pdb_seq_aligned',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
