# Generated by Django 5.1.3 on 2024-11-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0005_remove_antibioticresmutation_dna'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardmodel',
            table='card_models',
        ),
    ]
