# Generated by Django 5.1.3 on 2024-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0006_alter_pdb2gene_pdb_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb2gene',
            name='gene_seq_end',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='gene_seq_start',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='pdb_seq_end',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='pdb_seq_start',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
