# Generated by Django 5.1.3 on 2024-11-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0006_alter_cardmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antibioticresmutation',
            name='genes',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='taxonomy_id',
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='gene',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='bad_bac_exercise.gene'),
            preserve_default=False,
        ),
    ]
