# Generated by Django 5.1.3 on 2024-11-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0007_remove_antibioticresmutation_genes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antibioticresmutation',
            old_name='protein',
            new_name='mutation',
        ),
    ]
