# Generated by Django 5.1.3 on 2024-11-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0007_pdb2gene_gene_seq_end_pdb2gene_gene_seq_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdb2Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_in_pdb', models.CharField(blank=True, max_length=100, null=True)),
                ('drug_residue_name', models.CharField(blank=True, max_length=3, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.drug')),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.pdbstructure')),
            ],
            options={
                'db_table': 'pdb_2_drug',
            },
        ),
        migrations.AlterField(
            model_name='pdbstructure',
            name='drugs',
            field=models.ManyToManyField(through='bad_bac_exercise.Pdb2Drug', to='bad_bac_exercise.drug'),
        ),
    ]
