# Generated by Django 5.1.3 on 2024-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0008_rename_protein_antibioticresmutation_mutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
