# Generated by Django 5.1.3 on 2024-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0009_alter_gene_gene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugclass',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
