# Generated by Django 5.1.3 on 2024-11-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0011_alter_drug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='gene_name',
            new_name='name',
        ),
    ]
