# Generated by Django 5.1.3 on 2024-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0011_alter_pdb2mutation_dist_to_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb2mutation',
            name='dist_to_drug',
            field=models.FloatField(db_comment='Angstroms', null=True),
        ),
    ]
