# Generated by Django 5.1.3 on 2024-11-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0012_rename_gene_name_gene_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='inchi_key',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='smiles',
            field=models.TextField(null=True),
        ),
    ]
