# Generated by Django 5.1.3 on 2024-11-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0014_gene2ucscassembly_assembly_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticresmutation',
            name='assemblies',
            field=models.ManyToManyField(db_table='abrm_2_assembly', to='bad_bac_exercise.ucscassembly'),
        ),
    ]
