# Generated by Django 5.1.3 on 2024-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0014_rename_smiles_drug_canonical_smiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_discrete_structure',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
