# Generated by Django 5.1.3 on 2024-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0015_drug_is_discrete_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='aro_id',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='pubchem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='is_discrete_structure',
            field=models.BooleanField(null=True),
        ),
    ]
