# Generated by Django 5.1.3 on 2024-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0015_antibioticresmutation_assemblies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene2ucscassembly',
            old_name='assembly_end',
            new_name='end_on_contig',
        ),
        migrations.RenameField(
            model_name='gene2ucscassembly',
            old_name='assembly_start',
            new_name='start_on_contig',
        ),
        migrations.RenameField(
            model_name='gene2ucscassembly',
            old_name='assembly_strand',
            new_name='strand_on_contig',
        ),
        migrations.AddField(
            model_name='gene2ucscassembly',
            name='contig',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
