# Generated by Django 5.1.3 on 2024-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0016_rename_assembly_end_gene2ucscassembly_end_on_contig_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gene2ucscassembly',
            name='start_less_than_end',
        ),
        migrations.RemoveConstraint(
            model_name='gene2ucscassembly',
            name='both_columns_non_negative',
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('start_on_contig__lte', models.F('end_on_contig'))), name='start_less_than_end'),
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('start_on_contig__gte', 0), ('end_on_contig__gte', 0)), name='both_columns_non_negative'),
        ),
    ]
