# Generated by Django 5.1.3 on 2024-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0017_alter_pdbstructure_pdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbstructure',
            name='gene',
            field=models.ManyToManyField(db_table='pdb_2_gene', to='bad_bac_exercise.gene'),
        ),
    ]
