# Generated by Django 5.1.3 on 2024-11-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0018_pdbstructure_gene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdbstructure',
            old_name='gene',
            new_name='genes',
        ),
    ]
