# Generated by Django 5.1.3 on 2024-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0022_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibioticresmutation',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
