# Generated by Django 5.1.4 on 2025-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CARDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20, unique=True)),
                ('card_description', models.TextField()),
            ],
            options={
                'db_table': 'card_models',
                'db_table_comment': 'CARD refers to Comprehensive Antibiotic Resistance Database',
            },
        ),
        migrations.CreateModel(
            name='Decoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, 'phages'), (2, 'human_microbiome'), (3, 'plants')], db_comment='The meaning of the source fields: 1=pages, 2=human_microbiome, 3=plants')),
                ('identifier', models.CharField(max_length=30, null=True)),
                ('species_name', models.CharField(max_length=200, null=True)),
                ('dna_seq', models.TextField()),
            ],
            options={
                'db_table': 'decoys',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aro_id', models.CharField(max_length=7, null=True)),
                ('pubchem_id', models.IntegerField(null=True)),
                ('is_discrete_structure', models.BooleanField(null=True)),
                ('inchi_key', models.CharField(max_length=27, null=True)),
                ('canonical_smiles', models.TextField(null=True)),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'drug_classes',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('protein_seq', models.TextField()),
                ('dna_seq', models.TextField()),
            ],
            options={
                'db_table': 'genes',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.IntegerField(default=None, unique=True)),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.IntegerField(default=None, unique=True)),
                ('tax_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'taxonomy_names',
            },
        ),
        migrations.CreateModel(
            name='UCSCAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncbi_accession_number', models.CharField(max_length=50, unique=True)),
                ('refseq_assembly_id', models.CharField(max_length=50, unique=True)),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=100)),
                ('biosample', models.CharField(max_length=50)),
                ('bioproject', models.CharField(max_length=50)),
                ('assembly_date', models.DateField()),
            ],
            options={
                'db_table': 'ucsc_assemblies',
            },
        ),
        migrations.CreateModel(
            name='AntibioticResMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation', models.CharField(max_length=20)),
                ('flagged', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('card_models', models.ManyToManyField(db_table='abrm_2_card_model', to='bad_bac_exercise.cardmodel')),
                ('drugs_affected', models.ManyToManyField(db_table='abrm_2_drug', to='bad_bac_exercise.drug')),
                ('drug_classes_affected', models.ManyToManyField(db_table='abrm_2_drug_class', to='bad_bac_exercise.drugclass')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bad_bac_exercise.gene')),
                ('assemblies', models.ManyToManyField(db_table='abrm_2_assembly', to='bad_bac_exercise.ucscassembly')),
            ],
            options={
                'db_table': 'antibiotic_res_mutations',
                'db_table_comment': 'Mutations conferring antibiotic resistance',
            },
        ),
        migrations.CreateModel(
            name='Pdb2Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_in_pdb', models.CharField(blank=True, max_length=500, null=True)),
                ('drug_residue_name', models.CharField(blank=True, max_length=3, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.drug')),
            ],
            options={
                'db_table': 'pdb_2_drug',
            },
        ),
        migrations.CreateModel(
            name='Pdb2Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_chain', models.CharField(blank=True, max_length=4, null=True)),
                ('pct_identity', models.IntegerField(db_comment='Alignment identity')),
                ('gene_seq_aligned', models.TextField()),
                ('gene_seq_start', models.IntegerField()),
                ('gene_seq_end', models.IntegerField()),
                ('pdb_seq_aligned', models.TextField()),
                ('pdb_seq_start', models.IntegerField()),
                ('pdb_seq_end', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.gene')),
            ],
            options={
                'db_table': 'pdb_2_gene',
            },
        ),
        migrations.CreateModel(
            name='Pdb2Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_to_drug', models.FloatField(db_comment='Angstroms', null=True)),
                ('antibio_res_mutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.antibioticresmutation')),
            ],
            options={
                'db_table': 'pdb_2_mutation',
            },
        ),
        migrations.CreateModel(
            name='PDBStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4, unique=True)),
                ('abr_mutations', models.ManyToManyField(through='bad_bac_exercise.Pdb2Mutation', to='bad_bac_exercise.antibioticresmutation')),
                ('drug_classes', models.ManyToManyField(db_table='pdb_2_drug_class', to='bad_bac_exercise.drugclass')),
                ('drugs', models.ManyToManyField(through='bad_bac_exercise.Pdb2Drug', to='bad_bac_exercise.drug')),
                ('genes', models.ManyToManyField(through='bad_bac_exercise.Pdb2Gene', to='bad_bac_exercise.gene')),
            ],
            options={
                'db_table': 'pdb_structures',
            },
        ),
        migrations.AddField(
            model_name='pdb2mutation',
            name='pdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.pdbstructure'),
        ),
        migrations.AddField(
            model_name='pdb2gene',
            name='pdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.pdbstructure'),
        ),
        migrations.AddField(
            model_name='pdb2drug',
            name='pdb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.pdbstructure'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='publications',
            field=models.ManyToManyField(db_table='card_model_2_publication', to='bad_bac_exercise.publication'),
        ),
        migrations.CreateModel(
            name='Gene2UCSCAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_identity', models.IntegerField(null=True)),
                ('contig', models.CharField(max_length=50, unique=True)),
                ('start_on_contig', models.IntegerField(null=True)),
                ('end_on_contig', models.IntegerField(null=True)),
                ('strand_on_contig', models.IntegerField(choices=[(1, 'plus'), (2, 'minus')], null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.gene')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.ucscassembly')),
            ],
            options={
                'db_table': 'gene_2_ucsc_assembly',
            },
        ),
        migrations.AddField(
            model_name='gene',
            name='ucsc_assemblies',
            field=models.ManyToManyField(through='bad_bac_exercise.Gene2UCSCAssembly', to='bad_bac_exercise.ucscassembly'),
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30)),
                ('dna_seq', models.TextField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.ucscassembly')),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('start_on_contig__lte', models.F('end_on_contig'))), name='start_less_than_end'),
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('start_on_contig__gte', 0), ('end_on_contig__gte', 0)), name='both_columns_non_negative'),
        ),
    ]
