# Generated by Django 5.1.3 on 2024-11-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmed_id', models.IntegerField(default=None, unique=True)),
            ],
            options={
                'db_table': 'publications',
            },
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='publications',
            field=models.ManyToManyField(related_name='publication_2_card_model', to='bad_bac_exercise.publication'),
        ),
    ]
