# Generated by Django 5.1.3 on 2024-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0005_pdb2gene_gene_seq_aligned_pdb2gene_pdb_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb2gene',
            name='pdb_chain',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
