# Generated by Django 5.1.3 on 2024-11-29 19:03
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0013_alter_ucscassembly_refseq_assembly_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene2UCSCAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_identity', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.gene')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.ucscassembly')),
            ],
            options={
                'db_table': 'gene_2_ucsc_assembly',
            },
        ),
        migrations.AddField(
            model_name='gene2ucscassembly',
            name='assembly_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gene2ucscassembly',
            name='assembly_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gene2ucscassembly',
            name='assembly_strand',
            field=models.IntegerField(choices=[(1, 'plus'), (2, 'minus')], null=True),
        ),
        migrations.AlterField(
            model_name='gene2ucscassembly',
            name='pct_identity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('assembly_start__lte', models.F('assembly_end'))), name='start_less_than_end'),
        ),
        migrations.AddConstraint(
            model_name='gene2ucscassembly',
            constraint=models.CheckConstraint(condition=models.Q(('assembly_start__gte', 0), ('assembly_end__gte', 0)), name='both_columns_non_negative'),
        ),
    ]
