# Generated by Django 5.1.3 on 2024-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0017_remove_gene2ucscassembly_start_less_than_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(1, 'phages'), (2, 'human_microbiome'), (3, 'plants')])),
                ('identifier', models.CharField(max_length=30, null=True)),
                ('species_name', models.CharField(max_length=200)),
                ('dna_seq', models.TextField()),
            ],
            options={
                'db_table': 'decoys',
            },
        ),
    ]
