# Generated by Django 5.1.3 on 2024-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0018_decoy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoy',
            name='species_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
