# Generated by Django 5.1.3 on 2024-11-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0020_alter_decoy_table_comment'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='decoy',
            table_comment=None,
        ),
        migrations.AlterField(
            model_name='decoy',
            name='source',
            field=models.IntegerField(choices=[(1, 'phages'), (2, 'human_microbiome'), (3, 'plants')], db_comment='The meaning of the source fields: 1=pages, 2=human_microbiome, 3=plants'),
        ),
    ]
