# Generated by Django 5.1.4 on 2025-11-12 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0023_antibioticresmutation_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField(default=None, unique=True)),
                ('pmcid', models.CharField(default=None, max_length=20, unique=True)),
                ('title', models.TextField(default=None)),
                ('pub_year', models.IntegerField(default=None)),
                ('env_keywords_found', models.JSONField(default=list)),
                ('deposition_markers_found', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'env_publications',
            },
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='pdbs_available',
            field=models.ManyToManyField(through='bad_bac_exercise.Pdb2Mutation', to='bad_bac_exercise.pdbstructure'),
        ),
        migrations.CreateModel(
            name='EnvPublication2Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibio_res_mutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.antibioticresmutation')),
                ('env_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bad_bac_exercise.environmentpublication')),
            ],
            options={
                'db_table': 'env_publication_2_mutation',
            },
        ),
        migrations.AddField(
            model_name='environmentpublication',
            name='mutation',
            field=models.ManyToManyField(through='bad_bac_exercise.EnvPublication2Mutation', to='bad_bac_exercise.antibioticresmutation'),
        ),
        migrations.AddField(
            model_name='antibioticresmutation',
            name='env_publication',
            field=models.ManyToManyField(through='bad_bac_exercise.EnvPublication2Mutation', to='bad_bac_exercise.environmentpublication'),
        ),
    ]
