# Generated by Django 5.1.4 on 2025-11-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bad_bac_exercise', '0024_environmentpublication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentpublication',
            name='deposition_markers_found',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='environmentpublication',
            name='env_keywords_found',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='environmentpublication',
            name='pub_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='environmentpublication',
            name='title',
            field=models.TextField(default=None, null=True),
        ),
    ]
